// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SSC26",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SSC26",
            targets: ["AppModule"],
            bundleIdentifier: "AppleAcademy.SSC26",
            teamIdentifier: "6JH9DCVG6B",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .openBook),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                           .process("Resources")
                       ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
